# syntax=docker/dockerfile:1

# kasmweb/core-ubuntu-noble:1.18.0-rolling-daily 2026-03-30
ARG BASE_IMAGE="kasmweb/core-ubuntu-noble"
#ARG BASE_IMAGE_DIGEST="sha256:35c38a239ebe772e4cdcb89e041ed12375768a73d026afab1d712c5b9417541b"
# kasmweb/core-ubuntu-noble:1.18.0-rolling-daily 2026-04-07
#ARG BASE_IMAGE_DIGEST="sha256:c0088580fe69245fe6dd86a4f5651944333936508a76826b548e168d55ce2864"
ARG BASE_TAG="1.18.0-rolling-daily"
FROM ${BASE_IMAGE}:${BASE_TAG}
#FROM ${BASE_IMAGE}@${BASE_IMAGE_DIGEST} AS app_layer
USER root
SHELL ["/bin/bash", "-c"]

ARG DEV=0

ENV DEBIAN_FRONTEND=noninteractive \
    DEV=${DEV} \
    DOCKER_HOST=unix:///docker/docker.sock \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    HOME=/home/kasm-default-profile \
    INST_DIR=/root/src/kasm \
    INST_SCRIPTS="common/core/install/tools/install_tools_deluxe.sh \
                  common/core/install/tools/install_additional_tools.sh \
                  common/core/install/tools/install_dev_desktop_tools.sh \
                  ubuntu/install/dive/install_dive.sh \
                  ubuntu/install/chrome/install_chrome.sh \
                  ubuntu/install/sublime_text/install_sublime_text.sh \
                  ubuntu/install/vs_code/install_vs_code.sh \
                  common/core/install/new_startup/configure_startup.sh \
                  ubuntu/install/image_info/setup_image_info.sh \
                  common/core/install/setup_sudo/setup_sudo.sh \
                  ubuntu/core/install/update_default_profile/update_default_profile.sh \
                  common/core/install/gnome_keyring/enable_gnome_keyring.sh" \
    KASM_IMAGE_NAME="kasm-noble-dev-desktop" \
    STARTUPDIR=/dockerstartup \
    XDG_RUNTIME_DIR=/docker

WORKDIR ${HOME}

# Rootless DinD
RUN --mount=type=bind,target=/root/src/kasm,source=./src/kasm \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get upgrade -y && \
    bash ${INST_DIR}/ubuntu/install/dind_rootless/install_dind_rootless.sh && \
    cp ${INST_DIR}/ubuntu/install/dind_rootless/modprobe /usr/local/bin/modprobe && \
    chmod +x /usr/local/bin/modprobe && \
    mkdir -p ${XDG_RUNTIME_DIR} && \
    chown 1000:0 ${XDG_RUNTIME_DIR} && \
    mkdir -p /home/kasm-user/.config/docker && \
    cp ${INST_DIR}/ubuntu/install/dind_rootless/daemon.json /home/kasm-user/.config/docker/daemon.json && \
    chown -R 1000:0 /home/kasm-user/.config && \
    for SCRIPT in ${INST_SCRIPTS}; do \
        bash ${INST_DIR}/${SCRIPT} || exit 1; \
    done && \
    bash ${INST_DIR}/common/core/install/new_startup/add_startup_item.sh ${INST_DIR}/common/core/install/gnome_keyring/010-gnome-keyring.sh && \
    bash ${INST_DIR}/common/core/install/new_startup/add_startup_item.sh ${INST_DIR}/ubuntu/install/dind_rootless/300-dind_rootless && \
    ${STARTUPDIR}/set_user_permission.sh ${HOME} && \
    rm -f /etc/X11/xinit/XClients && \
    bash ${INST_DIR}/common/core/install/cleanup/cleanup.sh && \
    chown -R 1000:0 ${HOME} && \
    mkdir -p /home/kasm-user && \
    chown -R 1000:0 /home/kasm-user && \
    if [[ "${DEV:-0}" == "1" ]]; then \
        ls -alhR /home && \
        ls -alhR ${STARTUPDIR} && \
        env | sort; \
    fi

# Userspace Runtime
ENV HOME=/home/kasm-user \
    PATH="/home/kasm-user/.local/bin:${PATH}"
WORKDIR ${HOME}
USER 1000

CMD ["--tail-log"]
