# syntax=docker/dockerfile:1

ARG BASE_IMAGE="sgroesz/kasm-noble-dev-desktop"
ARG BASE_TAG="1.18.0-latest"
FROM ${BASE_IMAGE}:${BASE_TAG}

USER root

RUN --mount=type=bind,target=/root/src/kasm,source=./src/kasm \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get upgrade -y && \
    PATCH=1 bash /root/src/kasm/ubuntu/install/image_info/setup_image_info.sh

# Userspace Runtime
USER 1000

CMD ["--tail-log"]
