# syntax=docker/dockerfile:1

ARG BASE_IMAGE="kasmweb/core-ubuntu-noble"
ARG BASE_TAG="1.18.0-rolling-daily"
FROM ${BASE_IMAGE}:${BASE_TAG}
USER root
SHELL ["/bin/bash", "-c"]

ARG DEV=0

ENV DEBIAN_FRONTEND=noninteractive \
    HOME=/home/kasm-default-profile \
    DEV=${DEV} \
    INST_DIR=/root/src/kasm \
    INST_SCRIPTS=" \
                  common/core/install/tools/install_additional_tools.sh \
                  ubuntu/install/chrome/install_chrome.sh \
                  common/core/install/new_startup/configure_startup.sh \
                  ubuntu/install/image_info/setup_image_info.sh \
                  ubuntu/core/install/update_default_profile/update_default_profile.sh \
                  ubuntu/install/anycubic_slicer_next/install_anycubic_slicer_next.sh \
                  " \
    KASM_IMAGE_NAME="kasm-anycubic-slicer-next" \
    STARTUPDIR=/dockerstartup

WORKDIR ${HOME}

RUN --mount=type=bind,target=/root/src/kasm,source=./src/kasm \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get upgrade -y && \
    for SCRIPT in ${INST_SCRIPTS}; do \
        bash ${INST_DIR}/${SCRIPT} || exit 1; \
    done && \
    if [[ "${DEV:-0}" == "1" ]]; then \
        bash ${INST_DIR}/common/core/install/setup_sudo/setup_sudo.sh; \
    fi && \
    ${STARTUPDIR}/set_user_permission.sh ${HOME} && \
    rm -f /etc/X11/xinit/XClients && \
    bash ${INST_DIR}/common/core/install/cleanup/cleanup.sh && \
    chown -R 1000:0 ${HOME} && \
    mkdir -p /home/kasm-user && \
    chown -R 1000:0 /home/kasm-user && \
    if [[ "${DEV:-0}" == "1" ]]; then \
        ls -alhR /home && \
        ls -alhR ${STARTUPDIR} && \
        env | sort; \
    fi

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR ${HOME}
USER 1000

CMD ["--tail-log"]
