ARG BASE_TAG="1.18.0-latest"
ARG BASE_IMAGE="kasm-core-ubuntu-noble"
FROM sgroesz/${BASE_IMAGE}:${BASE_TAG}
USER root

ENV HOME=/home/kasm-default-profile \
    STARTUPDIR=/dockerstartup \
    INST_DIR=$STARTUPDIR/install
WORKDIR ${HOME}


######### Customize Container Here ###########

# This is a basic container to assist with creating new workspaces based on ${BASE_IMAGE}:${BASE_TAG}

# Enable SUDO
RUN echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Add some basic tools
## meld: File and folder comparison/diff
## mousepad: xfce text editor
RUN --mount=type=bind,target=/root/src/kasm,source=./src/kasm \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y meld mousepad && \
    rm -rf ${HOME}/.cache

######### End Customizations ###########


RUN chown 1000:0 $HOME

ENV HOME=/home/kasm-user
WORKDIR ${HOME}
RUN mkdir -p ${HOME} && chown -R 1000:0 ${HOME}

USER 1000

CMD ["--tail-log"]
